let x_1[1,1,1] = 0;
let x_1[1,2,1] = 3;
let x_1[1,3,1] = 6;
let x_1[1,4,1] = 10;
let x_1[1,5,1] = 15;
let x_1[1,6,1] = 20;
let x_1[1,7,1] = 24;
let x_1[1,8,1] = 28;

for {w in 1..W}
{
	for {i in 1..I}# watch out!!!!!!!!!!!!!!!!!!!!
	{
		if violate[w] == 1 then
		{
			break;
		}
		for {t in 0..T}
		{
			if violate[w] == 1 then
			{
				break;
			}
			for {r in 1..R}
			{
				if violate[w] == 1 then
				{
					break;
				}
				if t!=T && x_1[i,t,r,w]>x_1[i,t+1,r,w] then #b
				{
					let violate[w] := 1;
					display w;
					display "b";
				}
				if t!=T && r!=R && x_1[i,t+1,r+1,w]>x_1[i,t,r,w] then #c
				{
					let violate[w] := 1;
					display w;
					display "c";
				}
				if t!= 0 && sum{r_ in 1..R}(x_1[i,t,r_,w]-x_1[i,t-1,r_,w]) >z[t,w] then #d
				{
					let violate[w] := 1;
					display w;
					display "d";
				}
				if x_1[i,0,1,w] > z[0,w] then #e
				{
					let violate[w] := 1;
					display w;
					display "e";
				}
				if r!=R && t<=T-LT[i,r+1,w] && x_1[i,t,r,w]>x_1[i,t+LT[i,r+1,w],r+1,w] then #f
				{
					let violate[w] := 1;
					display w;
					display "f";
				}
	
				if LT[i,1,w]<=T && x_1[i,LT[i,1,w],1,w]!=1 then#g
				{
					let violate[w] := 1;	
					display w;
					display "g";				
				}
				if r!=1 && x_1[i,0,r,w] != 0 then#h
				{
					let violate[w] := 1;	
					display w;
					display "h";					
				}
				if x[i]!=x_1[i,0,1,w] then#i
				{
					let violate[w] := 1;
					display w;
					display "i";	
				}
				if x[i]<kesi[i] then#j
				{
					let violate[w] := 1;
					display w;
					display "j";	
				}
				
			}
		}
	}
}